name: generate Ascii Artwork

on: push

jobs: 
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        
        - name: Install Cowsaw Program
          run: sudo apt-get install cowsay -y
        
        - name: Execute cowsay CMD
          run: cowsay -f dragon "Run for cover, I am DRAGON.....RAWR" >> dragon.txt

        - name: test file exist
          run: grep -i "dragon" dragon.txt

        - name: Read file
          run: cat dragon.txt

        - name: checkout repo file
          run: ls -lrtha
        
        