name: generate Ascii Artwork

on: push

jobs: 
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
 

        - name: checkout repo file
          run: ls -lrtha
        
        - name: giving persmission
          run: chmod 777 ./ascii-srcipt.sh
          
        - name: Executing shell Script
          run: ./ascii-srcipt.sh

        
        
        