name : generate ascii Artwork

on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Install cowsay program
      run: sudo apt-get install cowsay -y

    - name: Execute Command CMD
      run: cowsay -f dragon "Run for cover, I am a DRAGON.....RAWR" >> dragon.txt

    - name: sleep for 30 seconds
      run: sleep 30

  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
    - name: sleep for 10 second
      run: sleep 10
    - name: test file exists
      run: grep -i "dragon" fragon.txt

  deploy_job_3:
    needs: test_job_2
    runs-on: ubuntu-latest
    steps:
    - name: Read file
      run: cat dragon.txt

    - name: Deploy
      run: echo Deploying....